# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
  - r: 3.2
  # R 3.1 has a broken NextMethod() mechanism
  # so summarise() won't work
  #- r: 3.1
